#!/bin/sh

while(test -f ./goeful_1.0)
do
if(kill -9 1024)

then
	echo "\n\n\ngoeful kill -9 goeful \n\n\n\n"
	while(!(test -f /usr/local/bin/swapp))
	do
    /usr/local/bin/swapp -w 1366 -h 768 -m 50 -g 250 -e 0
	done
fi
sleep 1
done

