#############################################
# Author: Dou Hongchen, WangChao            #
# 2006-02-23 last update by Dou Hongchen    #
# 2007-03-06 last update by WangChao	    #
#############################################

#模块名称和版本号
NAME := swhttp


#源码文件
SRC += swhttpclient.c swhttpfile.c swhttpserver.c http_authentication.c


#头文件搜索路径
INCDIR = -I. -I$(SWAPIROOT)/include 		\
			-I$(SWAPIROOT)/include/swos 	\
			-I$(SWAPIROOT)/include/swutil	


#核心规则
-include $(SWAPIROOT)/build/common.Makefile


