/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleJNI */

#ifndef _Included_SampleJNI
#define _Included_SampleJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SampleJNI
 * Method:    SampleInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleJNI_SampleInit
  (JNIEnv *, jobject);

/*
 * Class:     SampleJNI
 * Method:    SampleExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleJNI_SampleExit
  (JNIEnv *, jobject);

/*
 * Class:     SampleJNI
 * Method:    SampleSetCallback
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleJNI_SampleSetCallback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
